# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

model:
  trgt: unet
  dim: [1, 28, 28]
  n_channels: 32
  num_res_blocks: 1
  num_classes: 10
  class_cond: true

cpname: "tcfmunet"
classcond: true