# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

# use source/normal.yaml
defaults:
  # - ./source.normal
  - source: normal
  - _self_

# dataset
datadim: 2
batch_size: 256
n_samples: 16384
n_trainsteps: 16384
dataset: moons
datanoise: 0.05

optim:
  lr: 1e-3
  lr_min: 1e-4
lr_schedule: constant

model:
  time_varying: true
  in_features: ${datadim}
  out_features: ${datadim}
  hidden_features: [64, 64, 64, 64]
  freqs: 3 # how many frequencies to use for the time embedding

fmloss: lipman
n_ode: zuko

# logging
logger: null # neptune, wandb
tags: null
logfreq: 5000
evalfreq: 5000

wandb_run_name: fm
# variables we can access in our code
job_name: 'results'
# job_name: ${hydra:job.name}
config_name: ${hydra:job.config_name}
# Stores the command line arguments overrides
override_dirname: ${hydra:job.override_dirname}
