# @package _global_
# this @package directive solves any nesting problem (if this file is included in another folder)

defaults:
  # - ./source.normal
  - source: normal # normal, 8gaussian
  - model: mlp
  - _self_
  - data: moons

task: all # all, train, gif, sidebyside

datadim: 2

n_trainsteps: 10000
batch_size: 256
eval_batch_size: 2048
plot_batch_size: 1024
plot_integration_steps: 201 # for gif and sidebyside
eval_integration_steps: 100 # for training

use_slcf: true # True works better
use_ot: true

loss_scale: 1
lr: 0.001

# for some reason does not converge well
# maybe numerical instability?
# plim: [-0.5,1.5] # domain for plots
# source:
#   dmin: 0 # domain for data
#   dmax: 1

plim: [-7,7] # domain for plots
data:
  dmin: -5 # domain for data
  dmax: 5

source:
  data_dim: 2

# computational
force_cpu: false
savedir: null
runname: null

# log-prob, quiver (velocity field), trajectory
doplot: [False, False, True]

# logging
logger: null # neptune, wandb
tags: null
logfreq: 100
evalfreq: 1000
seed: 42
dtype: float32

wandb_run_name: FM
# variables we can access in our code
job_name: 'results'
# job_name: ${hydra:job.name}
config_name: ${hydra:job.config_name}
# Stores the command line arguments overrides
override_dirname: ${hydra:job.override_dirname}