# @package _global_

source: 
  trgt: gaussian

  # if data in [0, 1]
  # Sigma: [[0.1, 0.01], [0.01, 0.1]]
  # mu: [0.5, 0.5]
  
  # # if data in [-1, 1]
  # Sigma: [[1.0, 0.5], [0.5, 1.0]]
  # mu: [0.0, 0.0]

  # if data in [-7, 7]
  Sigma: [[5.0, 2.5], [2.5, 5.0]]
  mu: [0.0, 0.0]
  