# @package _global_

source: 
  trgt: mog

  # if data in [0, 1]
  mus: [[0.25, 0.25], [0.75, 0.75]]
  pis: [0.5, 0.5]
  sigmas: [[0.2, 0.2], [0.2, 0.2]]

  # # if data in [-1, 1]
  # mus: [[-0.5, -0.5], [0.5, 0.5]]
  # pis: [0.5, 0.5]
  # sigmas: [[0.2, 0.2], [0.2, 0.2]]

  # if data in [-7, 7]
  # mus: [[-3, -3], [3, 3]]
  # pis: [0.5, 0.5]
  # sigmas: [[0.5, 0.5], [0.5, 0.5]]
  