# @package _global_

source: 
  # if data in [0, 1]
  # covariance_matrix: [[0.5, 0.25], [0.25, 0.5]]
  # loc: [0.5, 0.5]

  # if data in [-7, 7]
  covariance_matrix: [[5.0, 2.5], [2.5, 5.0]]
  loc: [0.0, 0.0]

  trgt: multivariate
  